export const FETCH_RESTAURANT_DATA = 'FETCH_RESTAURANT_DATA';
export const SET_RESTAURANT_DATA_LOADING = 'SET_RESTAURANT_DATA_LOADING';
export const SET_RESTAURANT_DATA = 'SET_RESTAURANT_DATA';
export const REMOVE_RESTAURANT_ITEM = 'REMOVE_RESTAURANT_ITEM';
